### ISSUE TITLE
This plugin is still awesome

### ISSUE THREAD

**Issue by ktoh** [joezimjs/JZ-Publish-Subscribe-jQuery-Plugin#1]
I know you decided to discontinue supporting it, but I've been using the plugin for a few years on some projects and it's been bulletproof for me. 

Out of curiosity, were there any particular performance issues that caused you to stop supporting it?

I haven't come across any, and I still consider this a lightweight and elegant solution to client side publish-subscribe.  Thanks for this awesomeness!

**Comment by joezimjs** [comment]
Thank you for your kind words. I simply discontinued this plug in because I haven't touched it in a long time and I don't see the point to putting more effort into a solution that has several great alternatives.  If you have any questions or concerns or comments feel free to express them here. I will still do what I can to help, but I will not be proactively adding new features. 

I hope it continues to work well for you. :)

**Comment by ktoh** [comment]
@joezimjs no issues (which is why I keep using it) and no feature requests either (ditto). It's stood the test of time!

**Comment by joezimjs** [comment]
Good to hear. :smile:
